import type { TodoDatabase } from "./types";
import { getOffsetDateString, getTodayString, getTomorrowString } from "../services/date-service";

export function createEmptyDatabase(): TodoDatabase {
  return {
    schemaVersion: 1,
    projects: {},
    areas: {},
    cycles: {},
    labels: {},
    tasks: {},
  };
}

export function createInitialMockDatabase(): TodoDatabase {
  const today = getTodayString();
  const tomorrow = getTomorrowString();
  const dayAfterTomorrow = getOffsetDateString(2);
  const nextWeek = getOffsetDateString(7);

  return {
    schemaVersion: 1,
    projects: {
      "proj-tempo": {
        id: "proj-tempo",
        title: "Crisp Tempo Plugin",
        description: "Things 3 × Linear independent task manager for Obsidian",
        status: "active",
        priority: "high",
        startDate: today,
        targetDate: nextWeek,
        createdAt: Date.now() - 86400000 * 2,
        updatedAt: Date.now(),
        order: "a",
        color: "#5e6ad2",
      },
      "proj-craft": {
        id: "proj-craft",
        title: "Crisp Craft",
        description: "Block-based visual writing and canvas workbench",
        status: "active",
        priority: "medium",
        startDate: getOffsetDateString(-5),
        targetDate: nextWeek,
        createdAt: Date.now() - 86400000 * 5,
        updatedAt: Date.now(),
        order: "b",
        color: "#0eb39e",
      },
      "proj-anks": {
        id: "proj-anks",
        title: "ANKS Knowledge OS",
        description: "V9.0 Knowledge architecture and retrieval core",
        status: "active",
        priority: "high",
        startDate: getOffsetDateString(-10),
        targetDate: getOffsetDateString(14),
        createdAt: Date.now() - 86400000 * 10,
        updatedAt: Date.now(),
        order: "c",
        color: "#f59e0b",
      },
      "proj-site": {
        id: "proj-site",
        title: "Personal Portfolio & Blog",
        description: "Redesign personal site with Astro and Tailwind",
        status: "planned",
        priority: "low",
        createdAt: Date.now() - 86400000 * 20,
        updatedAt: Date.now(),
        order: "d",
        color: "#ec4899",
      },
    },
    areas: {
      "area-eng": { id: "area-eng", title: "Engineering", order: "a" },
      "area-prod": { id: "area-prod", title: "Product", order: "b" },
      "area-life": { id: "area-life", title: "Personal", order: "c" },
    },
    cycles: {
      "cycle-1": {
        id: "cycle-1",
        title: "Cycle 1 (Sep 28 – Oct 4)",
        startDate: today,
        endDate: nextWeek,
        status: "current",
      },
    },
    labels: {
      "lbl-arch": { id: "lbl-arch", name: "Architecture", color: "#6366f1" },
      "lbl-ui": { id: "lbl-ui", name: "UI/UX", color: "#06b6d4" },
      "lbl-bug": { id: "lbl-bug", name: "Bug", color: "#ef4444" },
      "lbl-perf": { id: "lbl-perf", name: "Performance", color: "#10b981" },
    },
    tasks: {
      "task-1": {
        id: "task-1",
        title: "Build task engine & status machine",
        description: "Implement immutable task transition logic (todo -> in_progress -> done/waiting/canceled) and validate orthogonality.",
        status: "in_progress",
        triage: "processed",
        availability: "anytime",
        priority: "high",
        projectId: "proj-tempo",
        cycleId: "cycle-1",
        focusDate: today,
        labels: ["Architecture"],
        createdAt: Date.now() - 3600000 * 4,
        updatedAt: Date.now(),
        order: "a",
      },
      "task-sub-1": {
        id: "task-sub-1",
        title: "Define Task & Project TypeScript interfaces",
        status: "done",
        triage: "processed",
        availability: "anytime",
        priority: "medium",
        parentTaskId: "task-1",
        createdAt: Date.now() - 3600000 * 3,
        updatedAt: Date.now(),
        completedAt: Date.now() - 3600000 * 2,
        order: "a",
      },
      "task-sub-2": {
        id: "task-sub-2",
        title: "Implement optimistic state update queue",
        status: "in_progress",
        triage: "processed",
        availability: "anytime",
        priority: "medium",
        parentTaskId: "task-1",
        createdAt: Date.now() - 3600000 * 2,
        updatedAt: Date.now(),
        order: "b",
      },
      "task-sub-3": {
        id: "task-sub-3",
        title: "Unit tests for state machine transitions",
        status: "todo",
        triage: "processed",
        availability: "anytime",
        priority: "low",
        parentTaskId: "task-1",
        createdAt: Date.now() - 3600000,
        updatedAt: Date.now(),
        order: "c",
      },
      "task-2": {
        id: "task-2",
        title: "Design task row & Linear-style micro-interactions",
        description: "Pixel-precise 38px row height, muted border hover, quick action reveal on hover, and circular status checkbox.",
        status: "todo",
        triage: "processed",
        availability: "anytime",
        priority: "high",
        projectId: "proj-tempo",
        focusDate: today,
        labels: ["UI/UX"],
        createdAt: Date.now() - 3600000 * 5,
        updatedAt: Date.now(),
        order: "b",
      },
      "task-3": {
        id: "task-3",
        title: "Submit Amazon compliance documentation",
        description: "Finalize EU GPSR and battery compliance filing before the quarterly window closes.",
        status: "todo",
        triage: "processed",
        availability: "anytime",
        priority: "urgent",
        dueDate: today,
        focusDate: today,
        createdAt: Date.now() - 86400000,
        updatedAt: Date.now(),
        order: "c",
      },
      "task-4": {
        id: "task-4",
        title: "Review ANKS Docs Sync compatibility matrix",
        description: "Confirm suite fact sync and verify public repository counts across vault documentation.",
        status: "todo",
        triage: "processed",
        availability: "anytime",
        priority: "medium",
        projectId: "proj-anks",
        focusDate: today,
        createdAt: Date.now() - 7200000,
        updatedAt: Date.now(),
        order: "d",
      },
      "task-5": {
        id: "task-5",
        title: "Draft Crisp Tempo product specification & v1 baseline",
        status: "done",
        triage: "processed",
        availability: "anytime",
        priority: "high",
        projectId: "proj-tempo",
        focusDate: today,
        createdAt: Date.now() - 86400000,
        updatedAt: Date.now(),
        completedAt: Date.now() - 3600000 * 2,
        order: "e",
      },
      "task-6": {
        id: "task-6",
        title: "Initialize TypeScript + Preact workspace shell",
        status: "done",
        triage: "processed",
        availability: "anytime",
        priority: "medium",
        projectId: "proj-tempo",
        focusDate: today,
        createdAt: Date.now() - 86400000,
        updatedAt: Date.now(),
        completedAt: Date.now() - 3600000,
        order: "f",
      },
      // Inbox items
      "task-inbox-1": {
        id: "task-inbox-1",
        title: "Buy monitor arm and cable management tray",
        description: "Need heavy-duty gas spring arm supporting 32-inch 4K screen.",
        status: "todo",
        triage: "inbox",
        availability: "anytime",
        priority: "none",
        createdAt: Date.now() - 1800000,
        updatedAt: Date.now(),
        order: "a",
      },
      "task-inbox-2": {
        id: "task-inbox-2",
        title: "Research Web Notifications API for Obsidian mobile",
        status: "todo",
        triage: "inbox",
        availability: "anytime",
        priority: "medium",
        createdAt: Date.now() - 7200000,
        updatedAt: Date.now(),
        order: "b",
      },
      "task-inbox-3": {
        id: "task-inbox-3",
        title: "Test Preact JSX rendering performance with 1000 items",
        status: "todo",
        triage: "inbox",
        availability: "anytime",
        priority: "high",
        createdAt: Date.now() - 3600000,
        updatedAt: Date.now(),
        order: "c",
      },
      // Upcoming items
      "task-up-1": {
        id: "task-up-1",
        title: "Benchmark SQLite vs JSON storage speed with 5,000 tasks",
        status: "todo",
        triage: "processed",
        availability: "anytime",
        priority: "medium",
        projectId: "proj-tempo",
        startDate: tomorrow,
        createdAt: Date.now() - 86400000,
        updatedAt: Date.now(),
        order: "a",
      },
      "task-up-2": {
        id: "task-up-2",
        title: "Design cycle carryover & automated sprint rollover",
        status: "todo",
        triage: "processed",
        availability: "anytime",
        priority: "low",
        projectId: "proj-tempo",
        startDate: dayAfterTomorrow,
        createdAt: Date.now() - 86400000,
        updatedAt: Date.now(),
        order: "b",
      },
      "task-up-3": {
        id: "task-up-3",
        title: "Crisp Suite v9.1 release and docs sync update",
        status: "todo",
        triage: "processed",
        availability: "anytime",
        priority: "urgent",
        projectId: "proj-anks",
        dueDate: nextWeek,
        createdAt: Date.now() - 86400000 * 2,
        updatedAt: Date.now(),
        order: "c",
      },
      // Waiting items
      "task-wait-1": {
        id: "task-wait-1",
        title: "Waiting for design review on token palette & typography",
        description: "Blocked waiting on confirmation of 6px vs 8px corner radii and contrast checks.",
        status: "waiting",
        triage: "processed",
        availability: "anytime",
        priority: "high",
        projectId: "proj-tempo",
        createdAt: Date.now() - 86400000,
        updatedAt: Date.now(),
        order: "a",
      },
      "task-wait-2": {
        id: "task-wait-2",
        title: "Waiting for Cloudflare Durable Object worker deployment",
        description: "Need production token binding before deploying license state verification.",
        status: "waiting",
        triage: "processed",
        availability: "anytime",
        priority: "urgent",
        projectId: "proj-craft",
        createdAt: Date.now() - 86400000 * 2,
        updatedAt: Date.now(),
        order: "b",
      },
      // Someday items
      "task-some-1": {
        id: "task-some-1",
        title: "Explore AI auto-triage for captured quick notes",
        description: "Evaluate local LLM embeddings to cluster inbox notes automatically.",
        status: "todo",
        triage: "processed",
        availability: "someday",
        priority: "low",
        createdAt: Date.now() - 86400000 * 7,
        updatedAt: Date.now(),
        order: "a",
      },
      "task-some-2": {
        id: "task-some-2",
        title: "Natural language date parser (e.g. 'tomorrow at 3pm')",
        status: "todo",
        triage: "processed",
        availability: "someday",
        priority: "medium",
        createdAt: Date.now() - 86400000 * 5,
        updatedAt: Date.now(),
        order: "b",
      },
    },
  };
}
